version: '3'
services:
  arangodb_cluster:
    # Currently needs to be community version as we do not build nightly enterprise builds (at least no ones I am aware of)
    image: arangodb/arangodb-preview:devel-nightly
    ports:
      - "8529:8529"
    environment:
      - ARANGO_ROOT_PASSWORD=""
      - ARANGO_NO_AUTH=false
    volumes:
      - ./data:/var/lib/arangodb3
      - ./secrets.jwt:/secrets
    command: arangodb --mode=cluster --local=true --auth.jwt-secret=./secrets/token

  auth_service:
    image: neunhoef/auth_grpc
    ports:
      - "9092:9092"
    volumes:
      - ./secrets.jwt:/secrets
    platform: linux/amd64

  gral_gae_arangodb_auth:
    # Uses ArangoDB as the authentication service
    image: gcr.io/gcr-for-testing/graph-analytics/gral:main
    ports:
      - "9999:9999"
    volumes:
      - ./secrets.jwt:/secrets.jwt
    platform: linux/amd64
    command: gral --bind-port 9999 --arangodb-endpoints http://arangodb_cluster:8529

  gral_gae_grpc_auth:
    # Uses GRPC docker service container (defined above) as the authentication service
    image: gcr.io/gcr-for-testing/graph-analytics/gral:main
    ports:
      - "1337:1337"
    volumes:
      - ./secrets.jwt:/secrets.jwt
    platform: linux/amd64
    command: gral --bind-port 1337 --auth-service http://auth_service:9092 --arangodb-endpoints http://arangodb_cluster:8529

  gral_gae_grpc_auth_unreachable:
    # Set's an GRPC endpoint as the authentication service that is not reachable
    image: gcr.io/gcr-for-testing/graph-analytics/gral:main
    ports:
      - "1336:1336"
    volumes:
      - ./secrets.jwt:/secrets.jwt
    platform: linux/amd64
    command: gral --bind-port 1336 --auth-service http://localhost:1234 --arangodb-endpoints http://arangodb_cluster:8529