version: '3'
services:
  arangodb_cluster:
    # Currently needs to be community version as we do not build nightly enterprise builds (at least no ones I am aware of)
    image: arangodb/arangodb-preview:devel-nightly
    ports:
      - "8529:8529"
    environment:
      - ARANGO_ROOT_PASSWORD=""
      - ARANGO_NO_AUTH=false
    volumes:
      - ./data:/var/lib/arangodb3
      - ./secrets.jwt:/secrets
    command: arangodb --mode=cluster --local=true --auth.jwt-secret=./secrets/token

  auth_service:
    image: neunhoef/auth_grpc
    ports:
      - "9092:9092"
    volumes:
      - ./secrets.jwt:/secrets
    platform: linux/amd64