[package]
name = "utilities"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.0"
reqwest = "0.12.2"
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.115"
tokio = "1.36.0"