#!/bin/bash

cecho(){
    RED="\033[0;31m"
    GREEN="\033[0;32m"  # <-- [0 means not bold
    YELLOW="\033[1;33m" # <-- [1 means bold
    CYAN="\033[0;36m"

    printf "${!1}${2} ${NC}\n" # <-- bash
}

killall -9 gral &> /dev/null
mkdir -p logs
cd ../
cecho "CYAN" "Starting docker and gral instances..."
cecho "CYAN" "-> Docker and gral logs will be saved in api_tests/logs folder (only for a single run)"

docker compose up -d &> api_tests/logs/docker.txt

# Integration tests now do require the wiki-Talk dataset to be loaded
(cd examples || return; npm install; ./scripts/downloadSingleDataset wiki-Talk; node main.js --graphName wiki-Talk -d true --mqs 100 --con 10 --verifyGraph true)

# If the target/release/gral binary does not exists, build it
if [ ! -f target/release/gral ]; then
    cecho "CYAN" "Building gral..."
    cargo build --release
fi

./target/release/gral --bind-port 9999 --arangodb-endpoints http://localhost:8529 --arangodb-jwt-secrets ./secrets.jwt &> api_tests/logs/arangodb_auth.txt &
./target/release/gral --bind-port 1337 --auth-service localhost:9092 --arangodb-endpoints http://localhost:8529 --arangodb-jwt-secrets ./secrets.jwt &> api_tests/logs/service_auth.txt &
./target/release/gral --bind-port 1336 --auth-service localhost:1234 --arangodb-endpoints http://localhost:8529 --arangodb-jwt-secrets ./secrets.jwt &> api_tests/logs/service_auth_unreachable.txt &

# TODO: Wait properly for the services to start
sleep 5