#!/bin/bash

#############################################
### ArangoDB
#############################################

# Currently it is expected that ArangoDB is running.

# Import data into ArangoDB
(
  cd ../examples || return
  npm i
  node main.js --graphName wiki-Talk -d true --mqs 500 --con 50
)

#############################################
### Gral
#############################################

# We will always load a new graph for every benchmark as our service is separated from the database
# and the loading itself should be part of the benchmark.

#############################################
### Neo4j
#############################################

(
  cd ../examples/neo4j || return
  node main.js --graphName wiki-Talk --dropGraph true --mqs 20 --concurrent 10
)

