name: "Publish Documentation"

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@main
      - name: Checkout
        uses: actions/checkout@v2 # Required to mount the Github Workspace to a volume
      - uses: addnab/docker-run-action@v3
        with:
          image: pseudomuto/protoc-gen-doc
          options: -v ${{ github.workspace }}/protodoc:/protodoc -v ${{ github.workspace }}/proto:/proto
          run: |
            protoc -I proto --doc_out=protodoc --doc_opt=protodoc/ourhtml.mustache,index.html proto/graphanalyticsengine.proto
      - name: Push generated documentation to another repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@v1.7.2
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: protodoc/
          destination-github-username: 'arangodb'
          destination-repository-name: 'graph-analytics'
          user-email: heiko@arangodb.com
          commit-message: See ORIGIN_COMMIT from $GITHUB_REF
          target-branch: main
      - name: Test get variable exported by push-to-another-repository
        run: echo $DESTINATION_CLONED_DIRECTORY

